export type QuizQuestion = {
  id: string;
  question: string;
  options: string[];
  answerIndex: number;
  explanation: string;
};

export const quizzesByModule: Record<string, QuizQuestion[]> = {
  "industry-map": [
    {
      id: "m1q1",
      question: "What is the main risk of buying many disconnected tools without a shared data model?",
      options: ["Faster campaign launch", "Inconsistent reporting and decision errors", "Lower storage costs", "Guaranteed attribution accuracy"],
      answerIndex: 1,
      explanation: "Without shared taxonomy and ownership, metrics fragment and decisions become unreliable.",
    },
    {
      id: "m1q2",
      question: "A practical first move in stack rationalization is:",
      options: ["Replace everything with one suite immediately", "Build a core/edge/legacy inventory with owners", "Pause all acquisition activity", "Delete legacy data"],
      answerIndex: 1,
      explanation: "You need visibility and ownership before making consolidation decisions.",
    },
    {
      id: "m1q3",
      question: "Scenario: 8.6% of vendors disappeared last year. What should you protect first?",
      options: ["Logo count", "Data contracts and reporting ownership", "Campaign volume at all costs", "Office location"],
      answerIndex: 1,
      explanation: "Contracts and ownership survive churn better than a list of tools.",
    },
    {
      id: "m1q4",
      question: "If two teams disagree on the stack map, what resolves the argument fastest?",
      options: ["Title hierarchy", "A shared inventory with renewal dates and owners", "Vendor demos", "A rebrand"],
      answerIndex: 1,
      explanation: "Concrete ownership and timing make the operating model visible.",
    },
  ],
  "customer-data": [
    {
      id: "m2q1",
      question: "Which is foundational for reliable lifecycle analytics?",
      options: ["Creative rotation", "Consistent event taxonomy", "Daily bid adjustments", "Audience expansion only"],
      answerIndex: 1,
      explanation: "A clean taxonomy is the base layer for attribution, segmentation, and journey logic.",
    },
    {
      id: "m2q2",
      question: "Why map anonymous-to-known identity transitions?",
      options: ["To reduce page load speed", "To improve continuity across touchpoints", "To remove first-party data", "To avoid consent collection"],
      answerIndex: 1,
      explanation: "Identity transitions connect behavior before and after authentication/conversion.",
    },
    {
      id: "m2q3",
      question: "Scenario: product analytics, CRM, and paid media disagree. What becomes system-of-record first?",
      options: ["The noisiest dataset", "The source tied to the critical launch decision", "The prettiest dashboard", "The oldest platform"],
      answerIndex: 1,
      explanation: "Pick the source that governs the decision and make it authoritative first.",
    },
    {
      id: "m2q4",
      question: "What best reduces schema drift over time?",
      options: ["More ad spend", "Named ownership and change approval", "Extra dashboards", "Shorter emails"],
      answerIndex: 1,
      explanation: "Ownership plus approval reduces accidental breaking changes.",
    },
  ],
  "crm-map-cdp": [
    {
      id: "m3q1",
      question: "In a composable architecture, what typically stays as source of truth?",
      options: ["Ad platform UI", "Data warehouse/lakehouse", "Email template builder", "Tag manager only"],
      answerIndex: 1,
      explanation: "Composable setups generally keep core customer data in the warehouse.",
    },
    {
      id: "m3q2",
      question: "A key tradeoff between suite and composable stack is:",
      options: ["No tradeoff exists", "Speed-to-value vs flexibility/control", "Only branding differences", "Only storage pricing"],
      answerIndex: 1,
      explanation: "Suite tools can move faster initially, while composable often improves control over time.",
    },
    {
      id: "m3q3",
      question: "Scenario: the board wants one platform. What risk should you state explicitly?",
      options: ["You will never need integrations", "You may trade control for speed", "Data quality becomes automatic", "Latency disappears"],
      answerIndex: 1,
      explanation: "Every architecture choice makes a visible tradeoff, especially around control and lock-in.",
    },
    {
      id: "m3q4",
      question: "Which workflow should stay real-time if freshness matters?",
      options: ["Quarterly finance close", "Triggered cart recovery", "Annual procurement review", "Static brand guidelines"],
      answerIndex: 1,
      explanation: "Time-sensitive triggers need low-latency activation.",
    },
  ],
  "programmatic-pipes": [
    {
      id: "m4q1",
      question: "What do sellers.json and supply chain object primarily improve?",
      options: ["Creative quality", "Supply path transparency", "Landing page speed", "Email deliverability"],
      answerIndex: 1,
      explanation: "They make intermediaries and seller identities more transparent in programmatic paths.",
    },
    {
      id: "m4q2",
      question: "If CPA rises after scaling open exchange, first action should be:",
      options: ["Increase bids everywhere", "Audit supply quality and path efficiency", "Turn off all retargeting", "Stop all measurement"],
      answerIndex: 1,
      explanation: "Quality and path inefficiencies are common drivers of performance decay at scale.",
    },
    {
      id: "m4q3",
      question: "Scenario: a reseller chain is opaque. What is the operator move?",
      options: ["Ignore it if clicks are cheap", "Exclude or downgrade the path until verified", "Raise frequency caps only", "Change the logo"],
      answerIndex: 1,
      explanation: "Opaque paths should not earn full trust without verification.",
    },
    {
      id: "m4q4",
      question: "What does ads.txt let publishers do?",
      options: ["Bid on creative", "Publicly declare authorised sellers", "Encrypt audiences", "Increase page speed"],
      answerIndex: 1,
      explanation: "ads.txt creates a public authorization list for buyers to inspect.",
    },
  ],
  "privacy-consent": [
    {
      id: "m5q1",
      question: "Consent mode mainly helps by:",
      options: ["Designing your cookie banner", "Adapting tag behavior to user consent choices", "Replacing legal review", "Eliminating all compliance obligations"],
      answerIndex: 1,
      explanation: "Consent mode consumes consent states and modifies measurement behavior.",
    },
    {
      id: "m5q2",
      question: "A resilient signal strategy typically uses:",
      options: ["Client-side tags only", "Hybrid client + server critical events", "No event tracking", "Only modeled data"],
      answerIndex: 1,
      explanation: "Hybrid pipelines improve reliability under browser/privacy constraints.",
    },
    {
      id: "m5q3",
      question: "Scenario: browser and server both send the same conversion. What must happen?",
      options: ["Count both for confidence", "Deduplicate with a shared event key", "Delete consent logs", "Lower the media budget"],
      answerIndex: 1,
      explanation: "Deduplication keeps browser and server events trustworthy.",
    },
    {
      id: "m5q4",
      question: "What is the safest fallback when deterministic tracking weakens?",
      options: ["Assume nothing changed", "Use modeled reporting and guardrail KPIs", "Remove reporting entirely", "Double the spend"],
      answerIndex: 1,
      explanation: "Modeled reporting plus guardrails preserves decision-making under data loss.",
    },
  ],
  measurement: [
    {
      id: "m6q1",
      question: "Why combine experiments with MMM and platform reports?",
      options: ["To avoid all uncertainty", "To triangulate decision confidence", "To remove finance from planning", "To reduce campaign volume"],
      answerIndex: 1,
      explanation: "Each method has bias; triangulation improves reliability of budget decisions.",
    },
    {
      id: "m6q2",
      question: "What is incrementality testing trying to isolate?",
      options: ["Total clicks", "Causal lift beyond baseline", "Audience size", "Ad server latency"],
      answerIndex: 1,
      explanation: "Incrementality estimates the additional impact caused by marketing activity.",
    },
    {
      id: "m6q3",
      question: "Scenario: platform ROAS improves but payback worsens. What governs budget?",
      options: ["The best-looking dashboard", "The measure tied to business value and causality", "The loudest channel owner", "The oldest attribution window"],
      answerIndex: 1,
      explanation: "Budget should follow the metric that best captures true value, not vanity lift.",
    },
    {
      id: "m6q4",
      question: "A holdout test is mainly used to estimate:",
      options: ["Creative colour preference", "Incremental impact versus a control", "Warehouse latency", "CRM field completeness"],
      answerIndex: 1,
      explanation: "Holdouts isolate causal lift by comparing treatment to control.",
    },
  ],
  lifecycle: [
    {
      id: "m7q1",
      question: "Suppression logic in journeys is used to:",
      options: ["Increase random message volume", "Prevent over-messaging and conflicts", "Disable segmentation", "Lower data quality"],
      answerIndex: 1,
      explanation: "Suppression prevents fatigue and contradictory messaging.",
    },
    {
      id: "m7q2",
      question: "If activation is weak, first fix should focus on:",
      options: ["Only top-funnel spend", "Early onboarding milestones", "Unrelated brand colors", "Removing all CRM fields"],
      answerIndex: 1,
      explanation: "Activation bottlenecks are often solved by improving early product/value moments.",
    },
    {
      id: "m7q3",
      question: "Scenario: declared identity and behaviour disagree. Which signal gets priority?",
      options: ["Whatever is easiest to export", "The signal closest to the decision use case", "The newest dashboard", "Neither signal ever"],
      answerIndex: 1,
      explanation: "Signal priority depends on the job, not the convenience of extraction.",
    },
    {
      id: "m7q4",
      question: "What should you exclude from a trigger set if it creates fatigue?",
      options: ["Only logo size", "Low-value, high-frequency events", "All behavioural data", "All defaults"],
      answerIndex: 1,
      explanation: "Trigger design should exclude noisy events that do not predict intent.",
    },
  ],
  "creative-ai": [
    {
      id: "m8q1",
      question: "High creative volume without governance often causes:",
      options: ["Guaranteed CPA improvement", "Noise and poor learning quality", "Perfect attribution", "Lower compliance risk"],
      answerIndex: 1,
      explanation: "Without hypotheses and promotion rules, you get output but weak insight.",
    },
    {
      id: "m8q2",
      question: "A strong winner-promotion policy should include:",
      options: ["No thresholds", "Predefined statistical and business gates", "Only designer preference", "Single-platform results only"],
      answerIndex: 1,
      explanation: "Promotion criteria should include both significance and business impact thresholds.",
    },
    {
      id: "m8q3",
      question: "Scenario: the best CTR creative does not improve revenue. What should you do?",
      options: ["Promote it anyway", "Judge it on downstream conversion or revenue", "Ignore the result", "Stop testing forever"],
      answerIndex: 1,
      explanation: "The winner should be the creative that improves the business outcome that matters.",
    },
    {
      id: "m8q4",
      question: "What makes component-based creative useful?",
      options: ["It removes judgment", "It generalizes across placements and contexts", "It guarantees one ad winner", "It eliminates testing"],
      answerIndex: 1,
      explanation: "Reusable components help scale across surfaces while preserving learning.",
    },
  ],
  "vendor-evaluation": [
    {
      id: "m9q1",
      question: "The most useful vendor scorecard combines:",
      options: ["Brand popularity only", "Capability fit, TCO, risk, and integration effort", "Only license price", "Only UI preference"],
      answerIndex: 1,
      explanation: "Decision quality requires multidimensional criteria, not sticker price alone.",
    },
    {
      id: "m9q2",
      question: "A governance charter helps mainly by:",
      options: ["Blocking all experimentation", "Controlling tool sprawl and ownership", "Eliminating procurement", "Avoiding security review"],
      answerIndex: 1,
      explanation: "Governance clarifies adoption gates and ownership to reduce stack entropy.",
    },
    {
      id: "m9q3",
      question: "Scenario: the board demands a 30% cost cut. What do you protect first?",
      options: ["The cheapest vendor", "Capabilities tied to measurable lift or control", "The loudest request", "The newest feature"],
      answerIndex: 1,
      explanation: "Protect the capabilities that still earn their keep.",
    },
    {
      id: "m9q4",
      question: "Which criterion is most dangerous to ignore in vendor selection?",
      options: ["Logo design", "Switching cost and data portability", "Meeting length", "Slide count"],
      answerIndex: 1,
      explanation: "If you cannot exit cleanly, the tool can become structural debt.",
    },
  ],
  capstone: [
    {
      id: "m10q1",
      question: "In a 90-day operating plan, what should be explicit?",
      options: ["Only goals", "Owners, milestones, and success metrics", "Only vendor names", "Only ad creatives"],
      answerIndex: 1,
      explanation: "Execution requires clear ownership and measurable checkpoints.",
    },
    {
      id: "m10q2",
      question: "A dual-track plan means:",
      options: ["Ignore fundamentals", "Run quick wins while hardening architecture", "Do only research", "Delay all campaign activity"],
      answerIndex: 1,
      explanation: "Dual-track balances immediate impact with long-term system health.",
    },
    {
      id: "m10q3",
      question: "Scenario: finance and growth disagree on the KPI tree. What should come first?",
      options: ["A prettier dashboard", "A shared decision rule and owner map", "More channels", "A new agency"],
      answerIndex: 1,
      explanation: "Shared rules and ownership resolve cross-functional disagreement.",
    },
    {
      id: "m10q4",
      question: "If you need to prove cross-channel contribution, what is the first discipline to set?",
      options: ["Attribution chaos", "A consistent measurement and review cadence", "Only creative testing", "No KPIs"],
      answerIndex: 1,
      explanation: "Contribution claims require a repeatable measurement rhythm.",
    },
  ],
};
